#!/bin/bash

# set path
export PATH=$PATH:$HOME/.local/bin:$HOME/.bin

# Load resources

xrdb -merge .Xresources

# Set up an icon tray
stalonetray &

# Fire up apps

xscreensaver -no-splash &

# Set background image with feh
feh --bg-scale /usr/share/backgrounds/warty-final-ubuntu.png &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi
